# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unrealestate', '0002_auto_20161211_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='nordic-house'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='/media/uploads/videos/'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to='/media/uploads/images/'),
        ),
    ]
