# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 16:25
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('unrealestate', '0008_investment'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='minimal_investment_amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='SGD', max_digits=12),
        ),
        migrations.AddField(
            model_name='project',
            name='minimal_investment_amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('SGD', 'Singapore Dollar')], default='SGD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Deposit'), (1, 'Withdrawal'), (2, 'Investment')]),
        ),
    ]
