# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unrealestate', '0010_auto_20170102_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
