# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 13:47
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('unrealestate', '0013_auto_20170121_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('preferred_price_currency', djmoney.models.fields.CurrencyField(choices=[('SGD', 'Singapore Dollar')], default='SGD', editable=False, max_length=3)),
                ('preferred_price', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='SGD', max_digits=12)),
                ('short_description', models.TextField()),
                ('size', models.CharField(max_length=255)),
                ('tenancy', models.BooleanField(default=False)),
                ('tenancy_agreement_length', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_proposals', to='unrealestate.AssetClass')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_proposals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectProposalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/images/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('project_proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='unrealestate.ProjectProposal')),
            ],
        ),
    ]
