# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 20:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('unrealestate', '0015_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover_image',
            field=models.ForeignKey(default=18, on_delete=django.db.models.deletion.CASCADE, related_name='covered_project', to='unrealestate.ProjectImage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='investment',
            name='value_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('SGD', 'Singapore Dollar'), ('USD', 'US Dollar'), ('CNY', 'Yuan Renminbi')], default='SGD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='project',
            name='goal_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('SGD', 'Singapore Dollar'), ('USD', 'US Dollar'), ('CNY', 'Yuan Renminbi')], default='SGD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='project',
            name='minimal_investment_amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('SGD', 'Singapore Dollar'), ('USD', 'US Dollar'), ('CNY', 'Yuan Renminbi')], default='SGD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('SGD', 'Singapore Dollar'), ('USD', 'US Dollar'), ('CNY', 'Yuan Renminbi')], default='SGD', editable=False, max_length=3),
        ),
    ]
