# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('unrealestate', '0016_auto_20170208_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='investment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='unrealestate.Investment'),
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='preferred_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('SGD', 'Singapore Dollar'), ('USD', 'US Dollar'), ('CNY', 'Yuan Renminbi')], default='SGD', editable=False, max_length=3),
        ),
    ]
