# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 21:31
from __future__ import unicode_literals

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('unrealestate', '0017_auto_20170211_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='goal_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('SGD', 'Singapore Dollar')], default='SGD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='project',
            name='minimal_investment_amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('SGD', 'Singapore Dollar')], default='SGD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='preferred_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('SGD', 'Singapore Dollar')], default='SGD', editable=False, max_length=3),
        ),
    ]
