# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 21:52
from __future__ import unicode_literals

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('unrealestate', '0018_auto_20170211_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('SGD', 'Singapore Dollar')], default='SGD', editable=False, max_length=3),
        ),
    ]
